# Generated by Django 3.1 on 2020-09-19 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_auto_20200919_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='itemOf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_item', to='todo.todolist'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
