# Generated by Django 3.1 on 2020-09-30 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todoitem_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
