# Generated by Django 3.1 on 2020-09-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20200930_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='deadline',
        ),
    ]
