# Generated by Django 3.1 on 2020-09-30 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_remove_todoitem_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
