# Generated by Django 3.1 on 2020-10-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20200930_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['deadline']},
        ),
    ]
